package com.cyperpunkred.ai.domain.model

data class Skills(
    val athletics: Int = 0,
    val brawling: Int = 0,
    val concentration: Int = 0,
    val conversation: Int = 0,
    val education: Int = 0,
    val evasion: Int = 0,
    val firstAid: Int = 0,
    val humanPerception: Int = 0,
    val languageStreet: Int = 0,
    val localExpert: Int = 0,
    val perception: Int = 0,
    val persuasion: Int = 0,
    val stealth: Int = 0,
    val streetwise: Int = 0,
    val pistol: Int = 0,
    val rifle: Int = 0,
    val shotgun: Int = 0,
    val meleeWeapon: Int = 0,
    val martialArt: Int = 0,
    val heavyWeapon: Int = 0,
    val pickLock: Int = 0,
    val pickPocket: Int = 0,
    val lockpicking: Int = 0,
    val decryption: Int = 0,
    val electronics: Int = 0,
    val cybersecurity: Int = 0,
    val techWeapon: Int = 0,
    val armorTech: Int = 0,
    val cybertech: Int = 0,
    val demolition: Int = 0,
    val driving: Int = 0,
    val pilotAir: Int = 0,
    val pilotGround: Int = 0,
    val riding: Int = 0,
    val basicTech: Int = 0,
    val paramedic: Int = 0,
    val autopsy: Int = 0,
    val language: Int = 0,
    val composition: Int = 0,
    val playInstrument: Int = 0,
    val photography: Int = 0,
    val tracking: Int = 0,
    val animalHandling: Int = 0,
    val survival: Int = 0
)
